####COLOR DEFINITIONS FOR RGB OLED ####

COLOR_WHITE     = "white"
COLOR_RED       = "#ff0000"
COLOR_YELLOW    = "#ffff00"
COLOR_BLUE      = "#000000"
COLOR_GREEN     = "#00ff00"
COLOR_BLUE      = "BLUE"

COLOR_SELECTED = COLOR_YELLOW
COLOR_SELECTED_OUTLINE = "black"
